### ISSUE TITLE
How could I define or invoke a workflow using my own structure

### ISSUE THREAD

**Issue by zc994646659** [albgar/aiida_siesta_plugin#128]
Hello, sir. @bosonie  Although I have successfully run an example and checked the results, I would like to ask for advice. It seems that protocols can define a workchain, but the code is quite complex. For instance, I have a CIF file, and I see that cif_bands can perform the calculation, but what exactly needs to be changed within it? Is there any interactive method that can more conveniently generate a .py file that I can submit?
zhouchao

**Comment by zc994646659** [comment]
@bosonie

**Comment by bosonie** [comment]
Hello. The examples in this project are just 'examples', they are there to facilitate the learning process of the users. A real project will for sure involve bits and pieces from several examples, and maybe even more.
AiiDA is built on top of python, and this gives maximum flexibility to users to do whatever they wants, using all the power of the python programming language.
A part from that, I don't think I can help more, I have no idea if there is a 'tool' that facilities you in the generation of submission scripts. I know that there is a web interface AiiDaLab https://www.aiidalab.net/ but I've never used it.
In any case, this is a general question, so I would suggest you to ask in the aiida discourse https://aiida.discourse.group/, where many users can help you find answers to your problems.

**Comment by bosonie** [comment]
Closing since this is not an issue of the code, but more a general question.
