### ISSUE TITLE
please rename pypi package to aiida-siesta

### ISSUE THREAD

**Issue by ltalirz** [albgar/aiida_siesta_plugin#15]
Please rename the pypi package to `aiida-siesta` here:
https://github.com/albgar/aiida_siesta_plugin/blob/a57b4940ef3ea3b75e9de968725cb82d328799c6/setup.json#L3
 in order to conform with all the [other aiida packages on pypi](https://pypi.org/search/?q=aiida).

Thanks!
Leo

**Comment by vdikan** [comment]
Hi Leo,

Recreating package repo manually on PyPI will break version history. 
I'll submit a request to the bug-tracker to rename it into `aiida-siesta`.

Regards,
 Vladimir

**Comment by ltalirz** [comment]
@vdikan I see there's now an `aiida-siesta` package - very good!
Could you please release the latest version there as well?

**Comment by albgar** [comment]
@ltalirz As far as I can see, the PyPi repository now contains the latest version of the plugin+workflows package, which is 0.9.10, updated yesterday. 
Perhaps you need an updated snippet in the AiiDA registry as well?

**Comment by ltalirz** [comment]
@albgar Ah sorry, I was looking at https://github.com/albgar/aiida_siesta_plugin/releases and I thought the latest release was 0.11.8 (version on pypi before was 0.11.5).
You can confirm that 0.9.10 is the latest version?

**Comment by albgar** [comment]
@ltalirz Yes. 0.9.10 is the latest version. We used to track the AiiDA version in the numbering, but we are no longer doing it. We will remain at 0.9.X with increasing X for now.
Sorry about the confusing numbers.

**Comment by ltalirz** [comment]
@albgar Thanks! This issue can be closed
