### ISSUE TITLE
Consider switching to gitflow model (develop branch)?

### ISSUE THREAD

**Issue by ltalirz** [albgar/aiida_siesta_plugin#32]
As of today, the AiiDA registry gets information on capability of aiida-siesta from the `setup.json` from the master branch fo the repository.

This means it currently reads version 1.0, while it isn't actually released yet
https://aiidateam.github.io/aiida-registry/plugins/siesta.html

Most plugins follow the gitflow model, where you develop things on the `develop` branch and merge into `master`, whenever you make a release. Perhaps would make sense here as well?

**Comment by bosonie** [comment]
Dear @ltalirz ,
The version is ready to be released, I just got caught in some personal problems last week and I couldn't conclude it. I'll do it tomorrow. Next time we will be more careful on the timing of "merge to master" and "make the release". We were actually reconsidering to call it 1.0b1. Could you give your opinion on that?

**Comment by ltalirz** [comment]
hi @bosonie, thanks for the quick update!

> I'll do it tomorrow. Next time we will be more careful on the timing of "merge to master" and "make the release".

No worries, this was just something I noticed and wanted to mention.

>  We were actually reconsidering to call it 1.0b1. Could you give your opinion on that?

If you go for 1.0.0b1, keep in mind that users doing `pip install aiida-siesta` will still get the old version (they will get the latest version only with `--pre`). So, the questions is whether this is what you would prefer.

Unless you are still planning severe API changes, I would personally lean towards `1.0.0` (and simply release bug fix releases if needed) but it's your choice.

**Comment by bosonie** [comment]
This is exactly my concern, but I saw that many plugins are still in beta. Our plugin has the phonon part missing, but all the other basic functionalities are ok. Thanks @ltalirz for the suggestion, we will decide tomorrow morning.

**Comment by ltalirz** [comment]
As long as the addition you are planning is backwards compatible (i.e. existing scripts using the plugin will continue to work) I wouldn't be too worried about releasing 1.0

**Comment by bosonie** [comment]
Sorted, we went for version 1.0.0. Thanks for your help @ltalirz.
