### ISSUE TITLE
Minor issues with setup.json pointed out by AiiDA registry

### ISSUE THREAD

**Issue by ltalirz** [albgar/aiida_siesta_plugin#77]
```
  >> WARNING: Missing classifier 'Framework :: AiiDA'
  >> WARNING: Entry point 'psf' does not start with 'siesta'
  >> WARNING: Entry point 'psml' does not start with 'siesta'
  >> WARNING: Entry point 'data.psf.family' does not start with 'siesta'
  >> WARNING: Entry point 'data.psml.family' does not start with 'siesta'
```

The first one should be easy to fix - for the others I would also suggest to think whether these entry points are really general enough not to be prefixed with `siesta`

**Comment by bosonie** [comment]
Hi @ltalirz. They are general enough and soon will be moved in the aiida-pseudo package.

**Comment by ltalirz** [comment]
Thanks @bosonie . 

Just a comment: I haven't seen anyone else use the `data` prefix. It seems to me that `psf.data`/`psml.data` would seem more logical, but you can address this when the code moves to the aiida-pseudo package.

**Comment by bosonie** [comment]
Thanks for the comment @ltalirz. It will be "pseudo.family.psf". I will close this issue when I fix the 'Framework :: AiiDA'.
